services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
  redis:
    image: redis:7.0.11
    restart: always
    ports:
      # just to avoid port conflicts with existing redis instances, we are moving down the port to 6378
      - "6378:6379"
    command: "redis-server"
